# Generated by Django 3.0.7 on 2020-06-21 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(choices=[('BOCA DO RIO', 'BOCA DO RIO'), ('CENTRO', 'CENTRO'), ('IMBUI', 'IMBUI'), ('PITUBA', 'PITUBA')], max_length=20)),
                ('fornecedor', models.CharField(max_length=40)),
                ('produto', models.CharField(max_length=40)),
                ('codigo_barra', models.BigIntegerField()),
                ('data_fabricacao', models.DateField()),
                ('data_validade', models.DateField()),
                ('custo_unidade', models.FloatField()),
                ('quant_compra', models.IntegerField()),
                ('preco_venda', models.FloatField()),
                ('quant_venda', models.IntegerField()),
                ('perecibilidade', models.CharField(choices=[('A', 'Alta'), ('N', 'Normal'), ('B', 'Baixa')], max_length=1)),
                ('foto_produto', models.ImageField(upload_to='images/')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
